CREATE TABLE employees
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    email_id character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    CONSTRAINT employees_pkey PRIMARY KEY (id),
    CONSTRAINT uk_employees_email_id UNIQUE (email_id)
);



